build:
  cuda_version: 12.1.1
  system_packages:
    - libssl-dev
    - libgl1
    - libglib2.0-0
  python_packages:
    - torch==2.2.1
    - vllm==0.4.1
    - transformers==4.40.1
    - absl-py==2.1.0
    - accelerate==0.29.2
    - aiofiles==23.2.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - albumentations==0.5.2
    - altair==5.2.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bidict==0.22.1
    - boto3==1.34.47
    - botocore==1.34.47
    - braceexpand==0.1.7
    - CacheControl==0.14.0
    - cachelib==0.12.0
    - cachetools==5.3.3
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.1.1
    - cryptography==42.0.5
    - cssselect==1.2.0
    - cssutils==2.9.0
    - cycler==0.12.1
    - diffusers==0.16.1
    - distlib==0.3.8
    - easydict==1.13
    - exceptiongroup==1.2.0
    - fastapi==0.104.1
    - ffmpy==0.3.1
    - filelock==3.13.1
    - firebase-admin==6.4.0
    - Flask==2.2.3
    - Flask-Cors==4.0.0
    - Flask-Session==0.6.0
    - Flask-SocketIO==5.3.6
    - flaskwebgui==0.3.5
    - fonttools==4.46.0
    - frozenlist==1.4.1
    - fsspec==2023.12.0
    - google-api-core==2.17.1
    - google-api-python-client==2.121.0
    - google-auth==2.28.2
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.0.0
    - google-cloud-core==2.4.1
    - google-cloud-firestore==2.15.0
    - google-cloud-storage==2.15.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.7.0
    - googleapis-common-protos==1.62.0
    - gradio==4.7.1
    - gradio_client==0.7.0
    - grpcio==1.62.1
    - grpcio-status==1.62.1
    - h11==0.14.0
    - httpcore==1.0.2
    - httplib2==0.22.0
    - httpx==0.25.2
    - huggingface-hub==0.19.4
    - hydra-core==1.3.2
    - idna==3.6
    - imageio==2.34.1
    - imgaug==0.4.0
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - intel-openmp==2021.4.0
    - itsdangerous==2.1.2
    - Jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - kiwisolver==1.4.5
    - kornia==0.5.0
    - kornia_rs==0.1.3
    - lazy_loader==0.4
    - lightning-utilities==0.11.2
    - loguru==0.7.2
    - lxml==5.1.0
    - Markdown==3.6
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.3
    - matplotlib==3.7.4
    - mdurl==0.1.2
    - mkl==2021.4.0
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - mysql-connector-python==8.3.0
    - networkx==3.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opencv-python==4.8.1.78
    - opencv-python-headless==4.9.0.80
    - orjson==3.9.10
    - packaging==23.2
    - pandas==2.0.3
    - piexif==1.1.3
    - Pillow==10.1.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==4.2.0
    - premailer==3.10.0
    - proto-plus==1.23.0
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydantic==2.7.1
    - pydantic_core==2.18.2
    - pyDeprecate==0.3.2
    - pydub==0.25.1
    - Pygments==2.17.2
    - PyJWT==2.8.0
    - PyMySQL==1.1.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-engineio==4.8.0
    - python-multipart==0.0.6
    - python-socketio==5.10.0
    - pytorch-lightning==2.2.4
    - pytz==2023.3.post1
    - PyWavelets==1.4.1
    - PyYAML==6.0.1
    - referencing==0.31.1
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rich==13.7.0
    - rpds-py==0.13.2
    - rsa==4.9
    - s3transfer==0.10.0
    - safetensors==0.4.2
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - shapely==2.0.4
    - shellingham==1.5.4
    - simple-websocket==1.0.0
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.27.0
    - sympy==1.12
    - tbb==2021.12.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tomlkit==0.12.0
    - toolz==0.12.0
    - torchmetrics==1.3.2
    - tqdm==4.66.1
    - typer==0.9.0
    - typing_extensions==4.12.0
    - tzdata==2023.3
    - uritemplate==4.1.1
    - urllib3==1.26.18
    - uvicorn==0.24.0.post1
    - virtualenv==20.25.1
    - webdataset==0.2.86
    - websockets==11.0.3
    - Werkzeug==2.2.2
    - wget==3.2
    - whichcraft==0.6.1
    - win32-setctime==1.1.0
    - wsproto==1.2.0
    - yacs==0.1.8
    - yagmail==0.15.293
    - yarl==1.9.4
    - zipp==3.17.0
    - rembg==2.0.57
    - pycryptodome==3.20.0