build:
  cuda_version: 12.1.1
  system_packages:
    - libgl1
    - libglib2.0-0
  python_packages:
    - Pillow==10.1.0
    - torch==2.2.1
    - transformers==4.40.1
    - opencv-python==4.8.1.78
    - opencv-python-headless==4.9.0.80
    - pydantic==2.7.1
    - pydantic_core==2.18.2
    - loguru==0.7.2
